package sop_corba.GestionProductosPackage;


/**
* sop_corba/GestionProductosPackage/ListProductoDTOHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* lunes 10 de junio de 2024 12:20:13 PM COT
*/

abstract public class ListProductoDTOHelper
{
  private static String  _id = "IDL:sop_corba/GestionProductos/ListProductoDTO:1.0";

  public static void insert (org.omg.CORBA.Any a, sop_corba.GestionProductosPackage.productoDTOCount[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static sop_corba.GestionProductosPackage.productoDTOCount[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = sop_corba.GestionProductosPackage.productoDTOCountHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (sop_corba.GestionProductosPackage.ListProductoDTOHelper.id (), "ListProductoDTO", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static sop_corba.GestionProductosPackage.productoDTOCount[] read (org.omg.CORBA.portable.InputStream istream)
  {
    sop_corba.GestionProductosPackage.productoDTOCount value[] = null;
    int _len0 = istream.read_long ();
    value = new sop_corba.GestionProductosPackage.productoDTOCount[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = sop_corba.GestionProductosPackage.productoDTOCountHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, sop_corba.GestionProductosPackage.productoDTOCount[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      sop_corba.GestionProductosPackage.productoDTOCountHelper.write (ostream, value[_i0]);
  }

}
