package sop_corba.GestionProductosPackage;

/**
* sop_corba/GestionProductosPackage/productoDTOCountHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* lunes 10 de junio de 2024 12:20:13 PM COT
*/

public final class productoDTOCountHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.GestionProductosPackage.productoDTOCount value = null;

  public productoDTOCountHolder ()
  {
  }

  public productoDTOCountHolder (sop_corba.GestionProductosPackage.productoDTOCount initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.GestionProductosPackage.productoDTOCountHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.GestionProductosPackage.productoDTOCountHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.GestionProductosPackage.productoDTOCountHelper.type ();
  }

}
