package sop_corba.GestionProductosPackage;


/**
* sop_corba/GestionProductosPackage/productoDTOCount.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* lunes 10 de junio de 2024 12:20:13 PM COT
*/

public final class productoDTOCount implements org.omg.CORBA.portable.IDLEntity
{
  public sop_corba.GestionProductosPackage.productoDTO producto = null;
  public int count = (int)0;

  public productoDTOCount ()
  {
  } // ctor

  public productoDTOCount (sop_corba.GestionProductosPackage.productoDTO _producto, int _count)
  {
    producto = _producto;
    count = _count;
  } // ctor

} // class productoDTOCount
