package sop_corba;


/**
* sop_corba/GestionProductos.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* jueves 23 de mayo de 2024 11:46:09 AM COT
*/

public interface GestionProductos extends GestionProductosOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionProductos
