package sop_corba;


/**
* sop_corba/GestionProductosOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* jueves 23 de mayo de 2024 11:46:09 AM COT
*/

public interface GestionProductosOperations 
{
  boolean registrarProducto (sop_corba.GestionProductosPackage.productoDTO objProducto);
  sop_corba.GestionProductosPackage.productoDTO consultarProducto (String codigo);
} // interface GestionProductosOperations
