package sop_corba;


/**
* sop_corba/GestionProductos.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* sábado 8 de junio de 2024 10:21:40 PM COT
*/

public interface GestionProductos extends GestionProductosOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionProductos
