package sop_corba;


/**
* sop_corba/ClienteInt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* jueves 30 de mayo de 2024 11:35:08 AM COT
*/

public interface ClienteInt extends ClienteIntOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ClienteInt
